apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-charts
  namespace: openshift-gitops
spec:
  project: default
  source:
    path: "."
    repoURL: https://github.com/ernesgonzalez33/bookinfo-charts.git
    targetRevision: main
    helm:
      valueFiles:
        - "values.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: bookinfo-charts
